#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Stapler is a pure-python tool for modifying PDF files."""

from staplelib import stapler


__author__ = 'Philip Stark, Fred Wenzel'
__license__ = 'BSD'
VERSION = (1, 0, 0)
__version__ = '.'.join(map(str, VERSION)) + 'rc1'


if __name__ == '__main__':
    stapler.main()
